pluginManagement {
    repositories {
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/public" }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "DebugInspector"

include ":inspector-api"
include ":inspector-core"
include ":inspector-ui"
include ":inspector-runtime"
include ":inspector-okhttp3"
include ":inspector-http"
include ":inspector-websocket"
include ":inspector-serial"
include ":inspector-database"
include ":inspector"
include ":inspector-no-op"
include ":sample-legacy"
