apply plugin: "com.android.application"

android {
    compileSdkVersion rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.allynav.debug.inspector.sample"
        minSdkVersion rootProject.ext.minSdk
        targetSdkVersion rootProject.ext.targetSdk
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        selective {
            initWith debug
            applicationIdSuffix ".selective"
            matchingFallbacks = ["debug"]
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation project(":inspector-api")
    debugImplementation project(":inspector")
    selectiveImplementation project(":inspector-http")
    selectiveImplementation project(":inspector-serial")
    releaseImplementation project(":inspector-no-op")
    implementation "com.squareup.okhttp3:okhttp:${rootProject.ext.okHttp3Version}"
    implementation "com.squareup.okio:okio:${rootProject.ext.okioVersion}"
}
