apply from: rootProject.file("gradle/android-library.gradle")

dependencies {
    implementation project(":inspector-core")
    compileOnly "com.squareup.okhttp3:okhttp:${rootProject.ext.okHttp3Version}"
    compileOnly "com.squareup.okio:okio:${rootProject.ext.okioVersion}"
    testImplementation "com.squareup.okhttp3:okhttp:${rootProject.ext.okHttp3Version}"
    testImplementation "com.squareup.okio:okio:${rootProject.ext.okioVersion}"
}
